/// <reference types="expo/types" />

// NOTE: This file is auto-generated by Expo and should not be edited manually.
// It is regenerated whenever you run `expo start` or `expo export`.
// See: https://docs.expo.dev/router/reference/typed-routes/
